### ISSUE TITLE
get_iers_eop()

### ISSUE THREAD

**Issue by ameliasamuel** [JuliaSpace/SatelliteToolbox.jl#102]
Hi,

When I try to run the examples in, for example, ecef_to_eci.jl:

eop_IAU2000A = get_iers_eop(Val(:IAU2000A))
r_ecef_to_eci(ITRF(), GCRF(), date_to_jd(1986, 06, 19, 21, 35, 0), eop_IAU2000A)

I get the error 'get_iers_eop' not defined. If I substitute fetch_iers_eop() it works fine, but I was wondering if I am making a mistake for the example to not run?

Thank you!

**Comment by ameliasamuel** [comment]
Thank you for clarifying! I found it in the ecef_to_ecef.jl, ecef_to_eci.jl etc. files in transformations (release-0.10).

**Comment by ronisbr** [comment]
Yes, the API changed a lot only after 0.11.
