### ISSUE TITLE
Drop all IERS EOP data functions and use EarthOrientation.jl

### ISSUE THREAD

**Issue by ronisbr** [JuliaSpace/SatelliteToolbox.jl#2]
The [EarthOrientation.jl](]https://github.com/JuliaAstro/EarthOrientation.jl) package already provide the feature to download and interpolate data from IERS. I need to test if the performance is equal or better and then drop the functions related to it from SatelliteToolbox.jl.

**Comment by helgee** [comment]
I did some benchmarking. Currently the functions in EarthOrientation.jl are bit slower.

- SatelliteToolbox.jl: ~30 ns
- EarthOrientation.jl (UT1-UTC): ~70 ns
- EarthOrientation.jl (others): ~60 ns

But they also use a more sophisticated interpolation scheme, i.e. Akima interpolation, and UT1-UTC is also more "correct", i.e. it is being interpolated as UT1-TAI which avoids jumps and correctly handles leap seconds.

Would that be acceptable for SatelliteToolbox.jl from a performance point of view?

**Comment by helgee** [comment]
Okay, new performance results after some tweaks 😄 

* EarthOrientation.jl (UT1-UTC): ~50 ns
* EarthOrientation.jl (others): ~26 ns

**Comment by ronisbr** [comment]
Hi @helgee ,

This is perfect! I will try to change the package to use EarthOrientation.jl in the following weeks.

Thanks for the info!

**Comment by ronisbr** [comment]
The package is not updated since 2021 and the tests are failing. Now that we rewrote the entire SatelliteToolbox.jl ecosystem, I think it is safer to keep with the current implementation.
