### ISSUE TITLE
Unable to change degree of gravity model

### ISSUE THREAD

**Issue by Adriaenvc** [JuliaSpace/SatelliteToolbox.jl#22]
Hi,

The n_max variable given to compute_g() doesn't get used, 
as in compute_dU() n_max gets overwritten by the '@unpack_GravityModel_Coefs gm_coefs' command.
Therefore the maximum degree of the gravity model is always used.

**Comment by ronisbr** [comment]
Thanks! Good catch. I will fix this today. The easiest way will be to unpack only the requires variables so that  `n_max` does not get overwritten.

**Comment by ronisbr** [comment]
Done! Thanks one more time. Btw, can you please test for me before I tag a new version?
