### ISSUE TITLE
fluxtable link broken

### ISSUE THREAD

**Issue by htyeim** [JuliaSpace/SatelliteToolbox.jl#34]
It seems that the ftp server below has some problems.
 ftp://ftp.geolab.nrcan.gc.ca/data/solar_flux/daily_flux_values/fluxtable.txt
When I used wget, it said "unable to resolve host address ‘ftp.geolab.nrcan.gc.ca’" 

----------
I think the new link might be 
ftp://ftp.seismo.nrcan.gc.ca/spaceweather/solar_flux/daily_flux_values/fluxtable.txt

**Comment by ronisbr** [comment]
Thanks! I will fix that :)

**Comment by ronisbr** [comment]
Done ! I will release a new version very soon.
