### ISSUE TITLE
Add a few simple, full examples to the docs

### ISSUE THREAD

**Issue by mihalybaci** [JuliaSpace/SatelliteToolbox.jl#47]
As a new user, I think it might be helpful if the to have a few examples that work through an entire problem start to finish. Something similar to the ISS example here https://www.ronanarraes.com/2019/01/the-satellite-toolbox-for-julia/ would be hugely beneficial to see in the docs.

**Comment by ronisbr** [comment]
Hi @mihalybaci 

Yes, you are completely right. The documentation is an area that needs a lot of improvements here.

**Comment by mihalybaci** [comment]
When I have learned more about the package, I would be happy to help with the examples since I will need to try out the simple examples anyway for learning purposes.

**Comment by ronisbr** [comment]
Perfect! Thanks! :)

**Comment by ronisbr** [comment]
After 3 years (!!), I managed to rewrite the entire ecosystem into smaller packages, and move the analysis functions to the package https://github.com/JuliaSpace/SatelliteAnalysis.jl

During the process, I documented everything I could and also created examples. You can check by looking at the documentation of each package. Hence, I think we can close this issue :)
