### ISSUE TITLE
How to cite SatelliteToolbox.jl?

### ISSUE THREAD

**Issue by PerezHz** [JuliaSpace/SatelliteToolbox.jl#49]
Hi!

First of all, thank you for this awesome package! We're currently using it in some of our research, and was wondering if there is any recommended way to include a citation? Is there any DOI or some other reference that we could use?

**Comment by ronisbr** [comment]
Hi @PerezHz !

Nice to hear that! I am glad this work is being useful :)

You can cite my paper in which I describe a satellite simulator I built at INPE using SatelliteToolbox.jl as a backend. In fact, building this simulator was the main driver that made me start SatelliteToolbox.jl.

https://doi.org/10.1177/1063293X18804006

**Comment by PerezHz** [comment]
Great, thanks!
