### ISSUE TITLE
Reference to geodesic coordinate frames

### ISSUE THREAD

**Issue by arbenede** [JuliaSpace/SatelliteToolbox.jl#66]
I think it would be very useful to add to the documentation a standard reference (textbook) where the coordinate systems mentioned in

https://juliaspace.github.io/SatelliteToolbox.jl/dev/man/transformations/ecef_eci/

are defined.

**Comment by ronisbr** [comment]
Hi @arbenede 

Sure! I will add. Everything is defined here:

Vallado, D. A (2013). Fundamentals of Astrodynamics and Applications. Microcosm Press, Hawthorn, CA, USA.

**Comment by arbenede** [comment]
Thanks @ronisbr, I am closing the issue.
