### ISSUE TITLE
Wrong docstring for rv_to_mean_elements_j2osc

### ISSUE THREAD

**Issue by ThatcherC** [JuliaSpace/SatelliteToolbox.jl#67]
It looks like the docstring for `rv_to_mean_elements_j2osc` is pretty much a duplication of `rv_to_mean_elements_sgp4` despite the functions being very different. For example, the j2osc docstring references BSTAR and `SGP4_GravCte`, neither of which are used in the j2osc function and neither of which are valid arguments to the j2osc function.

https://github.com/JuliaSpace/SatelliteToolbox.jl/blob/32effb7a08a4cf755832a303c9b2fd795fe3384b/src/orbit/mean_elements/j2osc.jl#L21-L60

**Comment by ronisbr** [comment]
You are 100% right! I will fix it.
