### ISSUE TITLE
Automatically download TLE

### ISSUE THREAD

**Issue by AlfredXiaSF** [JuliaSpace/SatelliteToolbox.jl#70]
I know there is a TLE reader. But it need user to provide TLE files or strings.
Can we automatically download TLE via NORID IDs and time range?

**Comment by ronisbr** [comment]
Hi @AlfredXiaSF !

This is a very nice feature that is not implemented in SatelliteToolbox.jl. This will require access to a free online service that has those historical TLEs. Do you know if such a service is available?

**Comment by AlfredXiaSF** [comment]
Hi @ronisbr !

Yes! There are several websites that can get TLEs, such as celestrak.com and Space-Track.org. Space-Track.org is the largest and most comprehensive.
There are several python packages that have implemented this feature, such as [satellitetle ](https://pypi.org/project/satellitetle/), [tle-download](https://pypi.org/project/tle-download/), [spacetrack](https://pypi.org/project/spacetrack/)

**Comment by ronisbr** [comment]
This can be closed!

The next version of SatelliteToolbox will use https://github.com/JuliaSpace/SatelliteToolboxTle.jl

This package will replace TLE support here and have the capability to fetch TLEs from CelesTrak.
