### ISSUE TITLE
Docstring update for getters functions

### ISSUE THREAD

**Issue by BlueTeo91** [JuliaSpace/SatelliteToolbox.jl#73]
Hello!

I noticed that in the docstrings of getters functions (e.g., get_i) it is not specified that the function call with SV can be done only using the ECI frame. It's a minor detail, but specifying it in the documentation it would improve the readability of the functions.

Thank you again for your work the Toolbox is really good :)

**Comment by ronisbr** [comment]
Hi @BlueTeo91 

You are 100% right! I will do this, thanks!

**Comment by ronisbr** [comment]
The API was completely modified for the upcoming split of SatelliteToolbox.jl into small modules. AFAIK, this problem does not exist anymore. Feel free to re-open if it is not the case!
