### ISSUE TITLE
IERS data service down

### ISSUE THREAD

**Issue by ThatcherC** [JuliaSpace/SatelliteToolbox.jl#78]
I've been getting the following error lately when trying to use the `get_iers_*()` funcitons:
```
[ Info: Downloading file 'EOP_IAU1980.TXT' from 'https://datacenter.iers.org/data/csv/finals.all.csv' with cURL.
┌ Warning: Download failed with error: failed process: Process(`/usr/bin/curl -s -R -o /tmp/jl_pg2hWY -L https://datacenter.iers.org/data/csv/finals.all.csv`, ProcessExited(60)) [60]
```

It looks like the issue is that the IERS datacenter.iers.org, data.iers.org and ftp.iers.org servers are down for maintenance (as of March 28, 2022):

![Screenshot from 2022-03-28 09-42-17](https://user-images.githubusercontent.com/2112477/160412619-aa2fc0a2-c2bf-47fd-924f-744e99aa0503.png)

(screenshot of IERS website from March 28, 2022 ~9:30 am)

The IERS gives the following backup URLS:
**EOP data:** http://hpiers.obspm.fr/eop-pc/

**Rapid EOP data and predictions:** https://maia.usno.navy.mil/

**Global geophysical fluids data:** http://loading.u-strasbg.fr/GGFC/ 

I mostly wanted to create this issue in case others are seeing the same issue. I'm not sure what the resolution for SatelliteToolbox.jl is - hopefully the regular IERS service just comes back up soon. Maybe a longer term strategy would be to have some fallback URLs for the IERS data in case the regular one is goes down? Or maybe we could get a mirror of the last day's IERS report hosted on Github? Not sure what the licensing implications of that would be but it would be nice to have a cached backup file on hand.

In the meantime I'm going to use the mirrors and report back any findings!

**Comment by ThatcherC** [comment]
For reference, it looks like Astropy uses the hpiers.obspm.fr url as a fallback: https://docs.astropy.org/en/stable/_modules/astropy/utils/iers/iers.html. That could be a good option here too!

**Comment by kshetline** [comment]
This link: http://hpiers.obspm.fr/eop-pc/

...refers me right back to https://maia.usno.navy.mil/ for IERS Bulletin A. I'm looking for a backup source for IERS Bulletin A, because ftp.iers.org has been down for a long time now, and as far as I know, might never be coming back.

**Comment by ronisbr** [comment]
Hi @ThatcherC and @kshetline !

Sorry for the late response, I completely missed this notification. I will check how can we update it inside SatelliteToolbox.jl to avoid those errors.

**Comment by ThatcherC** [comment]
I just came across [EarthOrientation.jl](https://github.com/JuliaAstro/EarthOrientation.jl) too - would it ever make sense to add that as a dependency for SatelliteToolbox? EarthOrientation.jl also only has URLs for the IERS files, but if we need to implement parsers for the new sources then maybe it makes more sense to do it just once in a specialized repo.

**Comment by ronisbr** [comment]
It was planned (see #2). However, I just did not have time to check how I can adapt it avoiding disruption in SatelliteToolbox.jl workflow.

**Comment by ThatcherC** [comment]
Ah got it. If was going to work on this for personal use (maybe to be pushed back as a PR if it works), would you recommend trying to add in alternative EOP sources to SatelliteToolbox directly, or pursuing the EarthRotation.jl and alternative sources approach? I'm not sure when I'd get around to it either, but it'd be nice to do it in a consistent way if I do!

**Comment by ronisbr** [comment]
I am rewriting SatelliteToolbox.jl to split it into smaller modules. The EOP is now handle in [SatelliteToolboxTransformations.jl](https://github.com/JuliaSpace/SatelliteToolboxTransformations.jl) that uses Scratch.jl. In this case, you can easily specified an URL if the default one is offline. I think we can close this issue but feel free to reopen if it is not the case.
