### ISSUE TITLE
Read eop from file

### ISSUE THREAD

**Issue by Tarlan0001** [JuliaSpace/SatelliteToolbox.jl#8]
I want to read eop file locally, because `ECItoECEF` and `ECEFtoECEF` doesn't work without eop.
I downloaded the eop file from [here](https://datacenter.iers.org/eop/-/somos/5Rgv/latest/224).

```
eop = read_iers_eop(eop_file, :IAU2000A)

ERROR: LoadError: MethodError: no method matching rECEFtoECEF(::Type{Val{:PEF}}, ::Type{Val{:ITRF}}, ::Float64, ::SatelliteToolbox.EOPData_IAU2000A{Interpolations.Extrapolation{Float64,1,Interpolations.GriddedInterpolation{Float64,1,Float64,Interpolations.Gridded{Interpolations.Linear},Tuple{Array{Float64,1}},0},Interpolations.Gridded{Interpolations.Linear},Interpolations.OnGrid,Interpolations.Flat}})
```

**Comment by ronisbr** [comment]
Hi @Tarlan0001,

IAU2000 reductions are not implemented yet. You should download and use the 1980 version.

**Comment by ronisbr** [comment]
You could get the file here:

https://datacenter.iers.org/eop/-/somos/5Rgv/latest/223

And read the file just using

    eop = read_iers_eop(eop_file)

**Comment by Tarlan0001** [comment]
`eop = read_iers_eop(eop_file)` gives different result than `eop = get_iers_eop()`. I copied the file from the URL you gave.

In addition,  `read_iers_eop()` causes lots of
```
WARNING: For performance reasons, consider using an array of a concrete type (eltype(A) == Any)
```

**Comment by Tarlan0001** [comment]
Is there a way not to use the EOP file, taking some average value?
I'm propagating to the future, and the current data is useless...

**Comment by helgee** [comment]
@Tarlan0001 What is your use case? If you are propagating far into the future, i.e. further than one year, it probably makes sense to use a lower precision Earth-fixed frame (e.g. `IAU_EARTH` in SPICE parlance).

**Comment by Tarlan0001** [comment]
Yes, I'm propagating further than 1 year.
Could you, please, explain in more detail what should I do for optimal solution?

**Comment by helgee** [comment]
@ronisbr Did you implement the IAU frame for the Earth? I have an implementation in `AstroDynCoordinates` but the package is currently not ready for public use.

**Comment by Tarlan0001** [comment]
Yes, my code
```
eop = read_iers_eop(eop_file)

function ECI_ECEF(y,date)

  D = rECItoECEF(J2000(), PEF(), date, eop)
  r_pef = D*y[1:3]
  v_pef = D*y[4:6] - [0;0;Ew] × r_pef
  a_pef = D*y[7:9] - [0;0;Ew] × [0;0;Ew] × r_pef - 2*[0;0;Ew] × v_pef

  D = rECEFtoECEF(PEF(), ITRF(), date, eop)
  r_itrf = D*r_pef
  v_itrf = D*v_pef
  a_itrf = D*a_pef

  return [r_itrf;v_itrf;a_itrf]

end

```

**Comment by ronisbr** [comment]
Hi @helgee,

Isn’t IAU adopted the ICRF? In this case, no. We have however the GCRF, which is almost the same. But everything is computed using IAU76/FK5 theory, not the more recent IAU2000 models.

I am planning to add IAU2000 in the following weeks.

**Comment by ronisbr** [comment]
Hi @Tarlan0001,

The difference between ITRF and PEF is that the former accounts for the polar motion, which is pretty much unmodelled AFAIK. The difference is not that much. The question is: do you really require ITRF? Isn’t PEF enough?

**Comment by ronisbr** [comment]
Notice that if you use only J2000 and PEF (original IAU76/FK5 theory), then you can just drop EOP data from the function you are using. The difference will be in the conversion from UT1 and Terrestrial Time, which will provide very little difference.
