### ISSUE TITLE
2023 Space Index File not available

### ISSUE THREAD

**Issue by rconnorjohnstone** [JuliaSpace/SatelliteToolbox.jl#87]
Running `init_space_indices()` currently errors when trying to download the 2023 Kp files, which don't yet exist on the Potsdam website that it's pulling them from.

**Comment by ronisbr** [comment]
Thanks for letting me know! I will add some `try..catch` to avoid those problems.

**Comment by ronisbr** [comment]
I am rewriting SatelliteToolbox.jl to split it into smaller modules. The space indices are now handle in [SpaceIndices.jl](https://github.com/JuliaSpace/SpaceIndices.jl) that uses Scratch.jl. I think we can close this issue but feel free to reopen if it is not the case.
