### ISSUE TITLE
sgp4 propagator accuracy

### ISSUE THREAD

**Issue by trufanov-nok** [JuliaSpace/SatelliteToolbox.jl#92]
Hi,
I'm new to julia and tried to reproduce my python calculations with this package. Unfortunately the results don't match with python's skyfield package.    
I have 2 TLE records (attached). [test.tle.zip](https://github.com/JuliaSpace/SatelliteToolbox.jl/files/10956321/test.tle.zip)
Julia code:   
```
using SatelliteToolbox
tles = read_tle("/home/truf/tests/test.tle")
o = init_orbit_propagator(Val(:sgp4), tles[1])
r, v = propagate!(o, 33208.95199608803)
```
result:
([-4.809400178348191e6, 4.756700552513811e6, 330.22513111666956], [675.0195082213636, 681.3381457850203, 7617.332409906825])

Python code:

```

from skyfield.api import EarthSatellite, load

line1 = "1 41386U 16016A   23049.16798291  .00026516  00000-0  30339-3 0  9998"
line2 = "2 41386  97.1815 134.9260 0010580 260.1146  99.8918 15.62057491388243"

line3 = "1 41386U 16016A   23049.55234578  .00023500  00000-0  26893-3 0  9994"
line4 = "2 41386  97.1814 135.3158 0010590 258.1661 101.8410 15.62074590388300"

ts = load.timescale()

satellite1 = EarthSatellite(line1, line2, '', ts)
satellite2 = EarthSatellite(line3, line4, '', ts)

# number of seconds
satellite2.epoch.utc_datetime().timestamp() - satellite1.epoch.utc_datetime().timestamp()

# propogate
geopos = satellite1.at(satellite2.epoch)

geopos.position.m
geopos.velocity.m_per_s
```

Results are:

```
>>> satellite2.epoch.utc_datetime().timestamp() - satellite1.epoch.utc_datetime().timestamp()
33208.95199608803

>>> geopos.position.m
array([-4784717.55451921,  4781517.86743171,    10831.07255969])
>>> geopos.velocity.m_per_s
array([ 695.52038204,  678.07536636, 7615.78105353])
```

They don't match.    
Am I missing something or sgp4 implementatons of SatelliteToolbox and skyfield produce dfferent results? If so, which implementation is correct?

**Comment by trufanov-nok** [comment]
Indeed! Thanks a lot for explanation and the code sample!

**Comment by ronisbr** [comment]
You're welcome!

**Comment by trufanov-nok** [comment]
It seems only sgp4 propagator contains api to read orbit from TLE directly while docs mention other propagators should support it to... Was this api overload removed for them?

**Comment by ronisbr** [comment]
Yes! It is a problem in the docs. A TLE is a set of mean elements for SGP4. I removed that interface so that we can avoid some errors.
