### ISSUE TITLE
Can't find ground_station_accesses in v0.10.0

### ISSUE THREAD

**Issue by esmith289** [JuliaSpace/SatelliteToolbox.jl#94]
This function was in v0.6.3 but can't find it in v0.10.0?

**Comment by esmith289** [comment]
same is true for list_ground_station_accesses

**Comment by ronisbr** [comment]
Hi @esmith289 !

The analysis functions are migrating to the package SatelliteAnalysis.jl.

I am changing the API **a lot**, and many breaking changes will happen in the near future. However, it will make everything much more consistent. Sorry about that.

**Comment by ronisbr** [comment]
By the way, `ground_station_access` is not `ground_facility_access` and the input/output is a lot different. You have now many options, including wrapping the result in a `DataFrame` to make further processing easier.

**Comment by esmith289** [comment]
Thank you very much Ronan, this is a great package!Sent from my iPhoneOn Mar 24, 2023, at 1:59 PM, Ronan Arraes Jardim Chagas ***@***.***> wrote:﻿
By the way, ground_station_access is not ground_facility_access and the input/output is a lot different. You have now many options, including wrapping the result in a DataFrame to make further processing easier.

**Comment by ronisbr** [comment]
Thanks @esmith289 !

I am really sorry for all those breakages. I have a much deeper knowledge about Julia language and its ecosystem than I had when the initial version of this package was released. Hence, I am doing a lot of improvements. I hope this phase ends soon :)

**Comment by esmith289** [comment]
It’s great stuff that you are doing. Sent from my iPhoneOn Mar 24, 2023, at 2:37 PM, Ronan Arraes Jardim Chagas ***@***.***> wrote:﻿
Thanks @esmith289 !
I am really sorry for all those breakages. I have a much deeper knowledge about Julia language and its ecosystem than I had when the initial version of this package was released. Hence, I am doing a lot of improvements. I hope this phase ends soon :)

**Comment by sydbon** [comment]
There are some issues we have been running into in regards to transitioning ground_station_accesses over to properly run in the SatelliteAnalysis package. Trying to alter the code that was in place for ground_station_accesses over to ground_facility_acesses create errors of "no method matching." I'm looking for a straight-forward way to translate the inputs of the ground_station_accesses to the new method (ground_facility_accesses) but documentation is limited.

**Comment by ronisbr** [comment]
Hi @sydbon !

I am in the middle of a rewriting of SatelliteAnalysis.jl. The current `dev` version has a new (more interesting) API. I think I will finish everything in one week or two. Until there, I suggest to keep using the old SatelliteToolbox.jl version.

**Comment by ronisbr** [comment]
But, if you want to try, add the development version of SatelliteAnalysis, and do:

```julia
julia> jd₀ = date_to_jd(2021, 1, 1)
2.4592155e6

julia> orb = KeplerianElements(
           jd₀,
           7130.982e3,
           0.001111,
           98.410 |> deg2rad,
           ltdn_to_raan(10.5, jd₀),
           π / 2,
           0
       )
KeplerianElements{Float64, Float64}:
           Epoch :    2.45922e6 (2021-01-01T00:00:00)
 Semi-major axis : 7130.98     km
    Eccentricity :    0.001111
     Inclination :   98.41     °
            RAAN :   78.4021   °
 Arg. of Perigee :   90.0      °
    True Anomaly :    0.0      °

julia> orbp = Propagators.init(Val(:J2), orb)
OrbitPropagatorJ2{Float64, Float64}:
   Propagator name : J2 Orbit Propagator
  Propagator epoch : 2021-01-01T00:00:00
  Last propagation : 2021-01-01T00:00:00

julia> ground_facility_accesses(orbp, (0, 0, 0))
2×3 DataFrame
 Row │ access_beginning         access_end               duration
     │ DateTime                 DateTime                 Float64
─────┼────────────────────────────────────────────────────────────
   1 │ 2021-01-01T10:20:03.144  2021-01-01T10:30:02.971   599.827
   2 │ 2021-01-01T22:49:55.887  2021-01-01T22:59:23.471   567.584
```

For more information and options, see the documentation of `ground_facility_accesses`.

**Comment by ronisbr** [comment]
Hi @esmith289 and @sydbon !

I just tagged v0.3.0 of the package https://github.com/JuliaSpace/SatelliteAnalysis.jl, which now contains the ground station algorithms. I also wrote the documentation about it. You can check it here:

https://juliaspace.github.io/SatelliteAnalysis.jl/dev/man/ground_facilities/ground_facility_accesses/
