### ISSUE TITLE
init_orbit_propagator method definition warning

### ISSUE THREAD

**Issue by gnadt** [JuliaSpace/SatelliteToolbox.jl#96]
Hi, during precompilation I get this warning: 

WARNING: method definition for #init_orbit_propagator#142 at .../.julia/packages/SatelliteToolbox/JX7R1/src/orbit/propagators/api/j2.jl:54 declares type variable T but does not use it.

**Comment by ronisbr** [comment]
Hi @gnadt !

SatelliteToolbox.jl is being rewritten in a modular fashion. I fixed many bugs, including this. However, it will take a while to release a new version. For the latest version, you can just ignore it.

**Comment by ronisbr** [comment]
I am rewriting SatelliteToolbox.jl to split it into smaller packages. This problem is now fixed.
